---
networks:
    # Used by traefik to expose the public services
    reverse-proxy:
        external: true

services:
    api:
        build:
            context: ../../
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: apistatox.api
        environment:
            ENV: prod
        expose:
            - 3000
        networks:
            - reverse-proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.apistatox.rule=Host(`api.statox.fr`)'
            - 'traefik.http.routers.apistatox.entrypoints=websecure'
            - 'traefik.http.routers.apistatox.tls=true'
