#!/usr/bin/env bash

URL=$(npx dotenvx get APIDB_URL)

# mysql://[user]:[password]@[host]:[port]/[db]
DATA_STR=$(echo "$URL" | sed -E 's;mysql://(.*):(.*)@(.*):(.*)/(.*);\1 \2 \3 \4 \5;')

user=$(echo "$DATA_STR" | cut -d ' ' -f1)
password=$(echo "$DATA_STR" | cut -d ' ' -f2)
host=$(echo "$DATA_STR" | cut -d ' ' -f3)
port=$(echo "$DATA_STR" | cut -d ' ' -f4)
db=$(echo "$DATA_STR" | cut -d ' ' -f5)

echo mysql --host="$host" --user="$user" --password="$password" --port="$port" "$db"
