#!/usr/bin/env bash

EXPECTED_USER="me@statox.fr"
CONNECTED_USER=$(npx heroku@latest whoami)

if [ "$CONNECTED_USER" != "$EXPECTED_USER" ]; then
    echo "User not logged in. Use 'npm run heroku:login'"
    exit 1
fi

# URL=$(npx heroku config:get JAWSDB_URL)
URL=$(npx heroku@latest config:get APIDB_URL)

# mysql://[user]:[password]@[host]:[port]/[db]
DATA_STR=$(echo "$URL" | sed -E 's;mysql://(.*):(.*)@(.*):(.*)/(.*);\1 \2 \3 \4 \5;')

user=$(echo "$DATA_STR" | cut -d ' ' -f1)
password=$(echo "$DATA_STR" | cut -d ' ' -f2)
host=$(echo "$DATA_STR" | cut -d ' ' -f3)
port=$(echo "$DATA_STR" | cut -d ' ' -f4)
db=$(echo "$DATA_STR" | cut -d ' ' -f5)

echo mysql --host="$host" --user="$user" --password="$password" --port="$port" "$db"
