/**
 *
 * OpenAPI properties map https://openapi-map.apihandyman.io/
 */
import fs from 'node:fs';
import { DateTime } from 'luxon';
import { Route } from '../../routes/types.js';
import { slog } from '../logging/index.js';

const OPENAPI_FILE_PATH = './src/views/openapi_json.mustache';

const generateDefinition = (routes: Route<unknown, unknown>[]) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const openApi: any = {
        openapi: '3.0.3',
        info: {
            title: 'api.statox.fr',
            version: '1.0.0',
            'x-creationDate': DateTime.now().toISO()
        },
        paths: {},
        components: {
            schemas: {},
            securitySchemes: {
                'apikey-iot': { type: 'apiKey', in: 'header', name: 'authorization' },
                // TODO these was (probably incorrectly) generated by a LLM
                user2: { type: 'https', scheme: 'cookie' }
            }
        }
    };

    const sortRoutes = (a: Route<unknown, unknown>, b: Route<unknown, unknown>) => {
        if (a.path === b.path) {
            return a.method < b.method ? -1 : 1;
        }

        return a.path < b.path ? -1 : 1;
    };
    for (const route of routes.sort(sortRoutes)) {
        let inputSchema;
        const { method, path, outputSchema, authentication } = route;
        if (method === 'post') {
            inputSchema = route.inputSchema;
        }

        // Initialize path if needed
        if (!openApi.paths[path]) openApi.paths[path] = {};

        // Build operation object
        openApi.paths[path][method] = {
            operationId: `${method}_${path.replace(/\//g, '_')}`,
            security: authentication && authentication !== 'none' ? [{ [authentication]: [] }] : [],
            requestBody: inputSchema
                ? {
                      required: true,
                      content: {
                          'application/json': {
                              schema: inputSchema
                          }
                      }
                  }
                : undefined,
            responses: {
                200: {
                    content: {
                        'application/json': {
                            schema: outputSchema
                        }
                    }
                }
            }
        };
    }
    return openApi;
};

export const initOpenapi = (routes: Route<unknown, unknown>[]) => {
    slog.log('app', 'init openapi');
    const openApi = generateDefinition(routes);
    fs.writeFileSync(OPENAPI_FILE_PATH, JSON.stringify(openApi, null, 2));
};
